port: ":5700"
app-name: "golang-api-starter"
mode: "debug"
key: 38ffad36bb01c6193c4e941343e179a772611a7acb33523b8eb9ba6a9bbd5f3d
db:
  username: localenv
  password: localenv
  host: localhost
  port: 5400
  name: localenv
  version: 1

allowed_origins:
  - http://localhost:8080


redis:
  url: "localhost:6379"
  password: "localenv"