version: '3.8'

services:
  db: # Database service
    image: docker.io/library/postgres:alpine # Use the official PostgreSQL image with Alpine Linux
    container_name: api_db # Assign a specific name to the container for easier identification
    ports:
      - 5400:5432 # Map port 5400 on the host to port 5432 inside the container (default PostgreSQL port)
    environment:
      - POSTGRES_USER=localenv # Set the default PostgreSQL user (can be overridden by environment variables)
      - POSTGRES_PASSWORD=localenv # Set the password for the default user (can be overridden)
      - POSTGRES_DB=localenv # Set the default database name (can be overridden)
    volumes:
      - apidata:/var/lib/postgresql/data # Mount a named volume 'apidata' to persist database files outside the container

volumes:
  apidata: {} # Define the named volume 'apidata' used by the 'db' service