// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: app.sql

package db

import (
	"context"
)

const getApplicationName = `-- name: GetApplicationName :one
SELECT id, name FROM "application" LIMIT 1
`

func (q *Queries) GetApplicationName(ctx context.Context) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationName)
	var i Application
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
